src/unit/engine/TAPTestEngine.php
Simplified changes
/cc @malandrew @crsmithdev
=> correct semantics of tap test engine

src/unit/engine/ConfigurableGolangTestEngine.php
From https://secure.phabricator.com/D13698
Tested on my devserver.
=> Renaming project_root to projectRoot for golang.

src/unit/engine/ConfigurablePytestTestEngine.php
From https://secure.phabricator.com/D13698
=> Fixing ConfigurablePytestTestEngine

src/lint/linter/UberStaticAnalysisLinter.php
Ref T243968. Fixes an issue where Xcode 7.2 is trying to analyze using the wrong build arch. Additionally make the simulator to run against a config option.
=> Fix static analysis for Xcode 7.2

src/lint/linter/UberObjCStyleCheckLinter.php, src/lint/linter/UberStaticAnalysisLinter.php
Fixes some relative path bugs so that the linters can be run from sub folders.
=> T239397 Allow objc linter to run from anywhere

src/land/UberSubmitQueueFuture.php
=> We were not parsing the SQ future result correctly. This fixes it

src/configuration/ArcanistSettings.php, src/workflow/ArcanistLandWorkflow.php
=> Adding unit engine to arc land

src/land/UberArcanistSubmitQueueEngine.php
This is causing more issues than help. Commenting out for the time being.
=> Commenting out comparing revisions

src/configuration/ArcanistSettings.php, src/workflow/ArcanistLandWorkflow.php
For monorepos, we only only certain folders to go through SQ. This gives an option to do that.
=> Arcanist changes to make SubmitQueue run only for a specific regex

src/workflow/ArcanistPatchWorkflow.php
SubmitQueue specific changes for merging
=> removing the squash option during merge

src/configuration/ArcanistSettings.php, src/workflow/ArcanistLandWorkflow.php, src/workflow/ArcanistTodoWorkflow.php
Currently there's no way of tracking changes that were tbred. We want to change that. As a first step, we will create maniphest tasks with the given set of project tags, and project members as subscribers.
=> Create maniphest task when tbring changes

src/configuration/ArcanistSettings.php, src/workflow/ArcanistLandWorkflow.php
=> Adding an option to not be able to override Harbormaster buildables

src/land/UberArcanistSubmitQueueEngine.php, src/workflow/ArcanistLandWorkflow.php
=> SubmitQueue Engine changes

src/unit/engine/UberFilesizeTestEngine.php
Any file which matches at least one given pattern is skipped from
filesize check.
=> Add "exclude_paths" parameter to UberFilesizeTestEngine.

src/unit/engine/UberFilesizeTestEngine.php
If "skip_lfs_files" config is tru for UberFilesizeTestEngine, then
it checks if the files exceeding the given filesize limit are tracked by
LFS. Large modified files that are tracked by LFS are ignored in this
unit test, as they will already get uploaded to LFS server.
=> Skip LFS files in UberFilesizeTestEngine.

src/workflow/ArcanistLandWorkflow.php, src/workflow/ArcanistSubmitWorkflow.php
Error message are like,
```
Fatal error: Undefined class constant 'REFTYPE_BOOKMARK' in /.../ArcanistSubmitWorkflow.php on line 225
```
=> Add missing class constants causing arc submit to fail

src/workflow/ArcanistSubmitWorkflow.php
=> Add --revision to `arc land`

src/lint/linter/UberCheckstyleLinter.php
Resolve absolute file path so that arc lint will work from any directory.
=> Resolve absolute file path so that arc lint can be run from any directory.

src/lint/linter/UberCheckstyleLinter.php
https://code.uberinternal.com/T1075791
=> Allow max files to use in checkstyle to be configurable and remove deprecation warning

src/land/ArcanistGitLandEngine.php, src/land/UberArcanistSubmitQueueEngine.php, src/lint/linter/UberCheckstyleLinter.php, src/workflow/ArcanistLandWorkflow.php, src/workflow/ArcanistSubmitWorkflow.php
Fixes previous issue with `arc submit` created as a result of this - https://github.com/uber/arcanist/pull/76
=> Adding support for arc land branchname in SubmitQueue

src/land/ArcanistGitLandEngine.php, src/land/UberArcanistSubmitQueueEngine.php, src/workflow/ArcanistLandWorkflow.php, src/workflow/ArcanistSubmitWorkflow.php
=> Revert "Adding support for arc land branchname in SubmitQueue"

src/land/ArcanistGitLandEngine.php, src/land/UberArcanistSubmitQueueEngine.php, src/workflow/ArcanistLandWorkflow.php, src/workflow/ArcanistSubmitWorkflow.php
=> Revert "Sundaram/fix land branchname feature"

src/unit/engine/TAPTestEngine.php
=> Read TAP coverage from project root.

src/lint/linter/UberShellCheckLinter.php
This will make shellcheck linter respect `severity` and `severity.rules` mapping (see https://secure.phabricator.com/book/phabricator/article/arcanist_lint/). 
For example, we can change severity of [SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086) error from `Advice` to `Error` by:
```
"uberShellCheckLinter": {
"type": "shellcheck",
....
"severity": {
"SC2086": "error"
}
}
```
Ref T1763487
=> Make shellcheck linter respect severity rules

src/workflow/ArcanistDiffWorkflow.php
Check-Prompt-Resolve (CPR) scripts are custom checks to be added
before unit and lint tests, which allow us to prompt the user to
run a (potentially heavyweight) fix script if a provided
lightweight check fails.
It adds the following optional entry type to `.arcconfig`:
```php
"uber.differential.check_prompt_resolve": [
{
"check-script" : "./path/to/quick_check.sh",
"prompt" : "[Explanation]. Fix it? (This can take a few minutes)",
"default-to" : true,
"resolve-script" : "./path/to/fix_script.sh"
}
]
```
For each object in the list, `arc diff` will run the `check-script`
unconditionally. If it succeeds, it will move on to the next CPR or
to lint/unit tests. If the check fails, it will prompt the user with
`prompt` and either [Y/n] (if `default-to` is `true`) or [y/N] (if
`default-to` is …
=> Add support for Check-Prompt-Resolve (CPR) scripts in arc diff.

src/land/UberArcanistStackSubmitQueueEngine.php, src/land/UberArcanistSubmitQueueEngine.php
Added support for remote.origin.pushurl being different from remote.origin.url
=> Added support for custom remote pushurl

src/configuration/ArcanistSettings.php, src/workflow/ArcanistLandWorkflow.php
This change is identical to https://github.com/uber/arcanist/pull/149 - but I have signed CLA so we can merge it
=> Remove sirmixalot from arcanist

src/flow/ICFlowWorkspace.php, src/flow/model/ICFlowFeature.php, src/flow/repository/ICGitAPI.php, src/flow/workflow/ICArcanistWorkflow.php, src/flow/workflow/ICTidyWorkflow.php
Teach `arc tidy` to fix branches with broken upstream branches
=> Add ability for `arc flow` to see commits in branch which are not amended

src/workflow/ArcanistPatchWorkflow.php
Commit message, author and revision description was not preserved when `--uber-merge-using-staging-tag` flag was used.
=> Fix uber-merge-using-staging-tag to preserve revision description

src/lint/linter/ArcanistGoLintLinter.php
Update golint install instructions to latest version
=> udpate golint install instructions

src/flow/model/ICFlowFeature.php
This change make sure that we do not cross branch fork boundaries to find revision this change belongs to, this way `arc tidy` will not misdetect `closed` branches.
=> Make sure that it is harder for `arc tidy` to delete branch which is not fully/yet `arc diff`ed

src/flow/workflow/ICArcanistWorkflow.php, src/flow/workflow/ICSyncWorkflow.php
We reuse getFeature functionality instead of using "semi-identical" functionality used in `arc sync`.
=> Teach `arc sync` to work with not amended commits in branches

src/flow/workflow/ICCascadeWorkflow.php
`arc cascade` should now fail with some instructions what to do further.
=> Print instructions about possibility to halt at conflict point when arc cascade fails to rebase

src/workflow/ArcanistLandWorkflow.php
=> Make newline instead of printing \n

src/land/UberArcanistStackSubmitQueueEngine.php
Make `arc lint` happy about that class
=> Make UberArcanistStackSubmitQueueEngine class a proper php

src/workflow/ArcanistLandWorkflow.php
Call custom API endpoint to validate if there are unreviewed paths by METADATA files on the repository. Ask user if he/she wants to continue if such paths exist.
=> imp: check if there are unreviewed paths by METADATA files

src/workflow/ArcanistLandWorkflow.php
IMP reviewers check will be performed only if env variable `ARC_BETA=1`.
=> Run IMP check only if ARC_BETA=1

src/flow/ICFlowWorkspace.php, src/flow/workflow/ICArcanistWorkflow.php, src/flow/workflow/ICFlowBaseWorkflow.php, src/flow/workflow/ICSyncWorkflow.php
This change also makes it easier for other commands to change root branch where tree of branches start
=> [arc flow] Make it possible to specify root branch for `arc sync` command

src/flow/workflow/ICArcanistWorkflow.php, src/flow/workflow/ICSyncWorkflow.php
If user forgets to `arc diff` some branch and run `arc sync` it will silently skip it, this change will start asking user if he/she wants to create Differential Revision.
=> [arc flow] If during `arc sync` we notice branch without Differential Revision try creating one

src/flow/workflow/ICSyncWorkflow.php
Add message to reduce confusion that process is finished
=> [arc flow] Add message that dependencies were updated, now it simply finishes work and users can be confused

src/land/UberArcanistSubmitQueueEngine.php
We shouldn't create any tasks in Phabricator
=> Phabricator as task tracking system is deprecated, stop creating task there

src/uber/UberFZF.php, src/uber/UberTask.php
=> [jira] Do not fail when `fzf` is not available, make warning clearly visible

src/uber/UberFZF.php, src/uber/UberTask.php
Allows engineer to enter jira issue ID not from provided list
=> [jira] Add support for entering jira issue ID which is not in the list

src/uber/UberTask.php
* Adds info how to skip adding issue
* Adds hint that you can enter issue ID not in the list
=> [jira] Add some extra hints into fzf header

src/configuration/ArcanistConfigurationManager.php, src/lint/linter/ArcanistCppcheckLinter.php, src/lint/linter/ArcanistScriptAndRegexLinter.php, src/lint/linter/ArcanistXMLLinter.php, src/lint/linter/__tests__/ArcanistLinterTestCase.php, src/lint/linter/xhpast/rules/ArcanistPHPCompatibilityXHPASTLinterRule.php, src/lint/linter/xhpast/rules/ArcanistParentMemberReferenceXHPASTLinterRule.php, src/lint/linter/xhpast/rules/ArcanistSelfMemberReferenceXHPASTLinterRule.php, src/parser/ArcanistBundle.php, src/parser/ArcanistDiffParser.php, src/repository/api/ArcanistGitAPI.php, src/unit/renderer/ArcanistUnitConsoleRenderer.php, src/workflow/ArcanistDiffWorkflow.php, src/workflow/ArcanistLiberateWorkflow.php, src/workflow/ArcanistWorkflow.php
This diff is based on the commits to fix php 8 errors of [phacility/arcanist](https://github.com/phacility/arcanist/commits/master)
Fixes : 
arc flow, arc diff, arc diff --preview, arc diff --nounit, arc diff --plan-changes, arc diff --only
`ERROR 8192: strlen(): Passing null to parameter #1 ($string) of type string is deprecated at [/opt/homebrew/Cellar/arcanist/tip/arcanist/src/configuration/ArcanistConfigurationManager.php:261]
arcanist(head=master, ref.master=125a0e72e653), phutil(head=stable, ref.stable=f61543b14309)
#0 ArcanistConfigurationManager::getUserConfigurationFileLocation() called at [<arcanist>/src/configuration/ArcanistConfigurationManager.php:174]
#1 ArcanistConfigurationManager::readUserConfigurationFile() called at …
=> Fixing Php 8.2 errors

src/configuration/ArcanistConfigurationManager.php, src/lint/linter/ArcanistCppcheckLinter.php, src/lint/linter/ArcanistScriptAndRegexLinter.php, src/lint/linter/ArcanistXMLLinter.php, src/lint/linter/UberCheckstyleLinter.php, src/lint/linter/__tests__/ArcanistLinterTestCase.php, src/lint/linter/xhpast/rules/ArcanistCommentStyleXHPASTLinterRule.php, src/lint/linter/xhpast/rules/ArcanistPHPCompatibilityXHPASTLinterRule.php, src/lint/linter/xhpast/rules/ArcanistParentMemberReferenceXHPASTLinterRule.php, src/lint/linter/xhpast/rules/ArcanistSelfMemberReferenceXHPASTLinterRule.php, src/lint/renderer/ArcanistConsoleLintRenderer.php, src/parser/ArcanistBundle.php, src/parser/ArcanistDiffParser.php, src/repository/api/ArcanistGitAPI.php, src/uber/UberTask.php, src/unit/renderer/ArcanistUnitConsoleRenderer.php, src/workflow/ArcanistAliasWorkflow.php, src/workflow/ArcanistDiffWorkflow.php, src/workflow/ArcanistLiberateWorkflow.php, src/workflow/ArcanistWorkflow.php
This updates the arcanist to be compatible with Php 8.2. libphutil also needs to be upgraded for this to actually work. (https://github.com/uber/libphutil/pull/28)
=> Upgrade to Php 8.2

src/workflow/CompareCommitToRevisionWorkflow.php
- stripped out context lines (since sometimes differences in patch context lines were triggering false positives). 
- normalized `rename` and `copy` to be `rename-or-copy`, since sometimes those would be different between the git patch and the revision patch. 
- refactored logic to save patch contents into a function, so it can be used on the "content matches" path to help debug things.
=> [arc] Updating compare-commit-to-revision to be less strict
