uber/arcanist

src/__phutil_library_map__.php, src/unit/engine/TAPTestEngine.php
`arc lint` was throwing an error:
```
File 'unit/engine/TAPTestEngine.php' mixes function
(unit_test_engine_get_lines, unit_test_engine_sort_lines) and
class/interface (TAPTestEngine) definitions in the same file. A file
which declares a class or an interface MUST declare nothing else.
```
Please test as I do not have project using this engine.
=> Fixed TAPTestEngine fit code standards.

src/lint/linter/UberStandardLinter.php
This PR fixes an uninitialized constant issue with uber standard. I honestly have no idea how this got broken because this used to work. 
cc: @sectioneight
=> Uber Standard uninitialized constant issue

src/lint/linter/ArcanistGoFmtLinter.php
Goimports is gofmt in steroids; automatically adding and removing imports for
you. It is API-compatible with gofmt, but better.
=> Use goimports for gofmt if available

src/lint/linter/ArcanistGoVetLinter.php
Previously:
Linting...
Exception
Linter "ArcanistGoVetLinter" generated a lint message that is invalid
because it does not have a name. Lint messages must have a name.
(Run with `--trace` for a full exception trace.)
Set name to the linter name, like the gofmt linter.
=> Fix Go Vet linter

src/lint/linter/UberStandardLinter.php
Name was added as a requirement to `ArcanistLintMessage` in https://secure.phabricator.com/D14165
I was getting this error:
```
[2016-05-12 23:13:10] EXCEPTION: (Exception) Linter "UberStandardLinter" generated a lint message that is invalid because it does not have a name. Lint messages must have a name. at [<arcanist>/src/lint/engine/ArcanistLintEngine.php:609]
arcanist(head=master, ref.master=2b9287eb53a4), phutil(head=master, ref.master=84b0feab4220)
#0 ArcanistLintEngine::validateLintMessage(UberStandardLinter, ArcanistLintMessage) called at [<arcanist>/src/lint/engine/ArcanistLintEngine.php:220]
#1 ArcanistLintEngine::run() called at [<arcanist>/src/workflow/ArcanistLintWorkflow.php:334]
#2 ArcanistLintWorkflow::run() called at [<arcanist>/scripts/arcanist.php:392]
```
=> Avoid erring while using uber-standard due to missing name key

src/lint/linter/ArcanistGoLintLinter.php
The linter currently ignores `severity.rules` and `severity` settings, categorizing everything as advice. This means that `arc lint` reports success regardless of the output of `golint`.
This fixes the linter to default these to errors and to respect the contents of `severity.rules`/`severity`.
Tested and confirmed locally.
@Pawka @prashantv
=> Make ArcanistGoLintLinter great again

src/lint/linter/UberObjCStyleCheckLinter.php
This makes it possible to specify a custom lint repo path relative to the project, otherwise it would need to be absolute and therefore different for each user.
=> Make the objc style check lint repo path relative to the project root

src/lint/linter/ArcanistGoVetLinter.php
Previously, if "go vet" failed to parse the input, since the output
format is different we'd call setLine() with something that's not a number.
=> Use a regex to handle go vet better

src/configuration/ArcanistSettings.php, src/land/UberArcanistSubmitQueueEngine.php, src/land/UberSubmitQueueClient.php, src/workflow/ArcanistLandWorkflow.php
The idea is to be able to send merge-requests to submitqueue, but still follow the original land pattern.
Context: We need to make sure SQ can handle the load etc.. for a given repository. And we want to do this in the most harmless fashion. The route we were able to think about was -> send merge_request metadata to SQ (which will handle the merge for the **shadow repo**), continue with the original land request. In order to achieve this, I have added an option that says 'enable_shadow'. if the shadow mode is on, then a secondary engine is created, and executed. The original engine is executed after the above is done.
=> Enable shadow mode for SubmitQueue.

src/land/UberArcanistSubmitQueueEngine.php, src/workflow/ArcanistLandWorkflow.php
1. Calling findRevision() now as part of uberGetRevision() as it has other
features like checking that the revision is up to date & checking to see if
harbormaster buildables have passed & reviewers have accepted the review etc..
2. Cleaning up SQ failover message
=> SQ Bug fixes

src/workflow/ArcanistPatchWorkflow.php
- What we want is the ability to cherry pick empty changes for SQ. 
- Initially we went with the merge strategy instead of cherry picking. But for release branches this is not ideal as you would end up picking up commits that are not in the release branch's history as they diverge a lot from the master branch.
=> Changing the way the uber-merge-strategy works

src/configuration/ArcanistSettings.php, src/workflow/ArcanistDiffWorkflow.php
ArcanistDiffWorkflow adds "--no-verify" flag to "git push" execution,
when code is pushed to staging area. This bypasses pre-push hook.
Git LFS uses pre-push hook to upload the files tracked by LFS to Git LFS
repo.
Make this configurable.
=> Add config to change --no-verify in git push in arc diff.

src/configuration/ArcanistSettings.php, src/workflow/ArcanistDiffWorkflow.php
When staging area is setup, arc diff invokes "git push" with staging
URI. Same staging URI is passed to pre-push hook. For Git LFS, pre-push
hook invokes git rev-list by passing the same URI with "--remotes="
parameter, where rev-list does not work with URIs.
This PR, checks "git remote -v" output, and replaces staging URI with
remote name instead, if there is a git remote defined for given staging
URI.
=> Replace staging uri with git remote name.

src/lint/linter/ArcanistGoFmtLinter.php
Goimports is doing weird things according to some coworkers, and
rewriting import order is a weird thing to do as part of a linter.
Changing this to be simpler.
=> Always use gofmt in gofmt linter

src/workflow/ArcanistDiffWorkflow.php
- specify mandatory field in .arcconfig as  `"differential.mandatory_fields": ["testPlan", "revertPlan"]`
- Throws an exception if not specified and exits the workflow.
=> Verify that the mandatory fields (testPlan, revertPlan)  are non empty when doing arc diff.

src/configuration/ArcanistSettings.php, src/workflow/ArcanistLandWorkflow.php
The added flag when enabled prevents developers from committing code that is not accepted.
=> Prevent developers from committing changes that are not committed

src/lint/linter/ArcanistPuppetLintLinter.php
%{linenumber} was deprecated long time ago and has been removed since puppet-lint 2.1.0
=> Use %{line} variable for puppet-lint log-format option

src/workflow/ArcanistLandWorkflow.php, src/workflow/ArcanistSubmitWorkflow.php
Add `--use-sq` support to allow opt-in even if submit-queue is not enabled on the repo.
=> Add --use-sq support

src/land/UberArcanistSubmitQueueEngine.php
we have some user interactive  hooks that depend on pre-push event (gather developer NPS, check/confirm breaking changes in IDL) .  the SubmitQueue engine does not currently emit these.  This to SubmitQueue will dispatch the event in the presence of a config value
=> SubmitQueueEngine dispatches pre-push event if configured

src/land/ArcanistGitLandEngine.php, src/land/UberArcanistSubmitQueueEngine.php, src/workflow/ArcanistLandWorkflow.php, src/workflow/ArcanistSubmitWorkflow.php
`Arc land ${branchname}` was broken for SubmitQueue workflows. This diff is expected to fix that.
The approach I have taken is the following:
1. While trying to land changes from another branch, the branch parameter is passed to UberArcanistSubmitQueueEngine.
2. SQEngine checks out the branch and then tries to find the revision of the branch. 
3. Once the revision is identified, it passes the parameters to SQ through a REST API call. 
4. Once the REST request is successful, the branch is deleted if it can be deleted and the onto branch to which the change is expected to pushed to is checked out. 
I have checked the following workflows as part of this change.
1. Normal SQ land for a dummy repo
2. SQ land from another branch using `arc land branchname`
3. Direct land and ticket creation …
=> Adding support for arc land branchname in SubmitQueue

src/lint/linter/UberCheckstyleLinter.php
- Script based java linting silently stopped catching problems after this commit:
https://github.com/uber/arcanist/commit/c52b050af7c85407e12bea666e4718075db8bedc
Rather than hackery to get the script setup working, let's just download the
checkstyle binary if it doesn't exist.  Currently folks are checking the checkstyle.jar into their repos so jenkins can autobuild with it and I'd like to avoid that.
- Improve checkstyleConfig handling
- PHP indentation standard is 2 spaces.  Fix (4 spaces)
- Move Java check out into it's own function
=> auto download java checkstyle jar if it doesn't exist

src/unit/engine/UberMavenTestEngine.php
Disable maven optimization.
The UberMavenTestEngine fails on multi-module projects because it is trying to minimize the projects built.  It goes into every project directory and tries to identify whether there are changes in the project before calling maven test.  However, when it changes to the child module directory, it doesn't recognize other modules within the same project.
Rather than go into the directory and build, we should identify the modules and use `-pl ` flag to run tests on certain modules.
=> Remove optimization for multi-module support

src/repository/api/ArcanistGitAPI.php
This mitigates an issue that is caused by commit metadata being interpreted as revision ids, and then an array is incorrectly dereferenced, causing `arc diff` to fail.
This only fixes the symptom. The root cause of invalid revision ids being gathered needs to be fixed.
1. Create a diff with `arc diff`.
2. Reset your local branch and `arc patch $NAME_OF_YOUR_DIFF_REVISION`.
3. Perform a change and commit it.
4. `arc diff` again. This should fail with the following error: `ERROR 8: Undefined offset: $NUMERIC_PORTION_OF_YOUR_DIFF_REVISION`
It was introduced when support for the `arc stack` command was included: 0e5599a106997d5754c691eedcce884736c99788
=> Fix undefined offset

src/__phutil_library_map__.php
Misspelled ESLintLinter as ESLingLinter. This pull request fixes this issue.
=> Fix typo in plugin map

src/workflow/ArcanistDiffWorkflow.php
When enabled, this change prompts the developer for whether a change is covered by a feature flag or not, and generates an initial revert plan for the diff appropriately.  We introduce two new `.arcconfig` settings:
1. `differential.revert_plan_check_paths`: A regular expression describing paths for which the revert plan templating should be enabled.  If this setting is absent, the feature is disabled.
2. `differential.revert_plan_ommitted_reasons`: An array of strings indicating possible reasons why a diff may not be covered by a feature flag.
The logic is mostly straightforward.  The only slightly-intrusive change is that since the revert plan templating should only apply to diffs modifying certain paths, we had to refactor the logic to call `generateChanges()` earlier when the …
=> Add support for enforcing a template for revert plans

src/workflow/ArcanistDiffWorkflow.php
Previously, if there was already a revert plan in the commit message of HEAD, we would still redundantly prompt the user for whether the diff is flagged, etc.
=> Don't prompt for revert plan if one already exists

src/workflow/ArcanistDiffWorkflow.php
7e8a278d3395c7315f0046a03ae79074a5c8eda3 introduced a bug where if `arc lint` amended HEAD with changes, those changes were not included in the submitted diff (though they were applied locally).  This PR fixes the bug by removing code that computed changes early, and instead relying on the repository API to determine if revert plan prompting should be applied.
=> Include amended changes in diff when revert plan checking is enabled

src/land/UberArcanistSubmitQueueEngine.php
`empty()` construct currently used in code is not compatible with 5.4 or older PHP versions, fix it to support those versions
=> Fix empty call which are not compatible with older php (like 5.4)

src/configuration/ArcanistSettings.php, src/workflow/ArcanistDiffWorkflow.php
This option has caused us some issues on SQ when developer ignores the prompt, this way at least people won't patch empty binary accidentally
=> Force failing on empty binary patch

src/lint/linter/ArcanistGoVetLinter.php
The 'go vet' command replaces 'go tool vet' in Go v1.12.
This change modifies the Arcanist lint commands to reflect
that command change.
=> Replace 'go tool vet' with 'go vet'

src/lint/linter/ArcanistGoVetLinter.php
Linter still executed `go tool vet` which is not supported since `go1.12`.
=> Actually execute 'go vet' in GoVetLinter

src/lint/linter/ArcanistNoopLinter.php
A recent change made the GOVET linter a no-op by replacing it with a call to the true command. But the path of the command is incorrect on macos, so this change uses `/usr/bin/env` to resolve the correct path.
=> Fix path to 'true'

src/lint/linter/ArcanistGoVetLinter.php
The older govet exposed ExternalLinter's options, so we should do the
same to maintain configuration backwards compatibility.
This was originally in #127, but #126's method was preferred over using `Filesystem`. This is a rebase of #127 on top of #126.
=> linter: govet: re-expose former options

src/workflow/ArcanistDiffWorkflow.php
After away reviewers check was added to `arc diff` flow, custom added `differential.mandatory_fields` check didn't work as expected anymore. Value of `$message` variable was changed to string during execution.
=> Fix mandatory_fields check on arc diff

src/workflow/ArcanistDiffWorkflow.php
Previously, a config block like this:
```
"uber.differential.check_prompt_resolve": [
{
"check-script" : "./tooling/arc/check_for_issue.sh",
"prompt" : "Fix?",
"default-to" : true,
"resolve-script" : "./tooling/arc/fix_script.sh"
}
],
```
Would work just fine when doing `arc diff` from the root of the repository, but produce the following output when run from a subdirectory:
```
sh: ./tooling/arc/dependencies-changed/check_for_issue.sh: No such file or directory
Fix? [Y/n]
```
And a further error if the user chose 'Y'.
This patch makes it possible to run `arc diff` with CPR scripts from anywhere within a repository.
=> Make CPR scripts always run relative to the repository root

src/lint/engine/ArcanistLintEngine.php, src/lint/linter/ArcanistLinter.php
The chunk size affects iOS repo arc performance heavily since we do some buck pre-loading in `WillLintPaths`. 
Anding an option to specify this in linter level would help ease the issue.
This option also comes up in the discussion in https://secure.phabricator.com/D12501, but never implemented since.
Local metrics with local iOS repo with:
```
git reset HEAD~10
arc lint
```
with chunk size of 32: 1m18.846s
with unbounded chunk size: 42s
a 46% drop down
=> allow linter to specify chunk size on linting large diffs

src/land/ArcanistGitLandEngine.php, src/repository/api/ArcanistGitAPI.php, src/workflow/ArcanistLandWorkflow.php
VFS for git can't work with submodules, so we check if we have submodules before trying. This way we avoid errors while at the same time not affecting repositories that actually have submodules.
=> Only update submodules when we have submodules

src/flow/workflow/ICSyncWorkflow.php
Uber (semi upstream) arcanist doesn't have `--skip-set-dependency` nor `--skip-decompose` options, it is default behavior actually. This unbreak `arc sync --revisions` functionality.
=> --skip-set-dependency and --skip-decompose is not needed

src/flow/workflow/ICFlowWorkflow.php, src/repository/api/ArcanistGitAPI.php
`arc flow` will mark "itself" whenever it is used and this way we will know that we should skip git.default-relative-commit setting set in `.arcconfig` this will make all repositories with that semi-redundant option compatible with `arc flow` workflow
=> arc flow depends on upstream branch setup but git.default-relative-commit in  is overriding everything, let's add workaround for it

src/workflow/ArcanistDiffWorkflow.php
Some of variables are javism not used in usual php code, convert camelcase to underscore based word separation, fix pht() warning
=> Satisfy linter issues

src/flow/workflow/ICGraftWorkflow.php
I only fixed one place in `graft` functionality which needed `activeDiff`, during testing another one was found
=> One more place in arc graft functionality where we need to query activeDiff

src/flow/ICFlowSummary.php
When there are no branches for `arc flow` to display it will return suggestion which is a bit misleading.
=> Improve error to stop confusing engineers how to use `arc flow`

src/flow/model/ICFlowFeature.php, src/flow/workflow/ICCascadeWorkflow.php
`arc cascade` tries alternative technique if usual `git rebase` fails, it uses `git rebase --onto` which is essentially cherry picks commits which were done in revision
=> Let `arc cascade` rebase differently if it knows to which differential revision branch belongs too

src/flow/workflow/ICCascadeWorkflow.php
We need to store exit code of rebaseOnto - otherwise if this strategy is successful - we still fail
=> Store rebaseOnto exit code,

src/land/UberArcanistStackSubmitQueueEngine.php, src/land/UberArcanistSubmitQueueEngine.php, src/workflow/ArcanistStackWorkflow.php
`arc stack` relies that stacked branches do not have more than 1 commit or those commits do not touch same files as stacked above change
=> Implement cherry-pick technique during `arc stack` lands

src/flow/workflow/ICSyncWorkflow.php
`arc sync` right now without any options passed is noop which is somewhat confusing
=> [arc flow] If no options are passed to `arc sync` - sync both dependencies and revisions

src/flow/workflow/ICCascadeWorkflow.php
`arc cascade` always cascades from current branch which might not be convenient when you do not want to switch to master just to make cascading rebases.
=> [arc flow] Add ability to specify from which branch to start cascading rebase

src/workflow/ArcanistLandWorkflow.php
Imp check introduced on #171 could be enabled only if `ARC_BETA` env variable was set to 1. Remove this condition and roll out feature to all users.
=> Publish imp check for everyone (Removed ARC_BETA env check)

src/workflow/ArcanistPatchWorkflow.php
`arc patch` was not pulling uber specific refs when simple `arc patch DXXXX` was executed, it was only pulling when specific diff was patched, make it work in all cases.
This will also improve staging support in jenkins as we will no longer need to actually setup staging and pull refs.
=> [arc patch] Fetch refs from repository if it is needed to patch changes

src/workflow/ArcanistDiffWorkflow.php
When new diff is created:
When diff is updated but title is still WIP:
=> When `wip` keyword is detected in differential revision title - offer to use Changes planned option which will silently create Diff

src/flow/workflow/ICSyncWorkflow.php
This change allows faster turnaround after rebase you can quickly publish changes to phabricator instead of waiting for each single unit/lint test before changes is published to phabricator
=> [arc flow] Make it possible to skip linting/unit tests and set plan-changes state when running `arc sync`

src/lint/linter/UberGitSecretsLinter.php
This removes the `binary` option, which is (1) unnecessary because `ArcanistExternalLinter` already includes a `bin` option, and (2) problematic because it does not correctly resolve binaries in paths relative to the root of the repository, unlike the existing `bin` option.
It also changes the "install instructions" to be more helpful and accurate.
=> Remove unnecessary 'binary' option; change install instructions

src/flow/field/ICFlowChangedLinesField.php, src/flow/model/ICFlowFeature.php, src/flow/workflow/ICCascadeWorkflow.php
`arc flow` was showing changes since last commit, if amend technique was used - changed lines was correct but if commit based flow in branch - incorrect, now it tries to show from revision start.
=> [arc flow] Changed lines reporting will correctly show changes since start of revision, rename BaseCommit to FirstCommit as it is more correct name

src/workflow/ArcanistPatchWorkflow.php
`arc patch --arcbundle` should in general be mostly local operation but there are cases when it actually needs access to phabricator.
Some more defailts: https://secure.phabricator.com/D20972
Issue is whenever - repo has no base commit - it tries to use phabricator API which has to be authenticated, by default `arc patch` is not trying to auth.
=> In `arc patch --arcbundle` workflow there might be a need to actually authenticate with Phabricator

src/unit/engine/ConfigurablePytestTestEngine.php
`ConfigurablePytestTestEngine` requires two "%s" placeholders (see https://github.com/uber/arcanist/blob/master/src/unit/engine/UberConfigurableTestEngine.php#L23) but does not template the test command with the coverage file path.
=> Template coverage command with cover tmp file.

src/flow/workflow/ICTidyWorkflow.php
`arc tidy` will print warning for deep branches:
```
[2020-04-03 14:40:38] ERROR 8: Undefined index: diff10 at [/home/artms/opt/arcanist/src/flow/workflow/ICTidyWorkflow.php:102]
arcanist(head=sync_diffs, ref.master=bba51dab73ed, ref.sync_diffs=0f2fad30f4e7), phutil(head=deployment, ref.master=9a9d94dc6ea7, ref.deployment=048e10231a43)
#0 ICTidyWorkflow::run() called at [<arcanist>/scripts/arcanist.php:394]
```
These branches are disconnected from master hence no point processing them anyway...
=> [arc flow] Do not process branches which are not know by arc flow

src/flow/workflow/ICGraftWorkflow.php
`arc graft` by default while reconstructing branch graph tries to patch closed Revision which usually crash due to "empty" commit and similar issue, change default to actually never do it unless explicitly asked.
=> [arc flow] Change graft default from always trying to patch closed/landed Revision to not do it by default

src/workflow/ArcanistStackWorkflow.php
Preparing state was ignored by `arc stack`, it is essentially state where tests are not yet started
=> [arc stack] Add new state of harbormaster builds to check against during `arc stack` lands

src/flow/workflow/ICTidyWorkflow.php
Passing glue string after array is deprecated
=> Linting fixes for deprecated call

src/workflow/ArcanistPatchWorkflow.php
`--arcbundle` doesn't actually exercise authorization workflow because it doesn't need anything from Phabricator before this point and fails fatally when 401 status code from uSSO is returned, make it compatible with old behavior when auth errors were simply ignored
=> Handle fatal error with uSSO enabled case when `arc patch` is used with `--arcbundle`

src/workflow/ArcanistDiffWorkflow.php
Adds functionality which will ask engineer to add task if configuration requires, it will only ask until first commit of message happens  afterwards no checks will be done. This should ensure minimal disruption for engineer. Common ways to automate execution are handled.
=> [arc diff] Check if task/issue is attached if differential.check_task_presence config option is present

src/uber/UberUSSO.php
Add help link to the error message which is thrown when `usso` binary is not found.
=> usso: extend error message with help link

src/uber/UberTask.php
Some users actually want to make edits in web, so to break flow as little as possible - after task is created - it is immediately opened in browser
=> Open create jira issue in browser to keep similar to old behavior

src/flow/ICFlowWorkspace.php, src/flow/field/ICFlowChangedLinesField.php, src/flow/field/ICFlowHashField.php, src/flow/field/ICFlowStatusField.php, src/flow/model/ICFlowFeature.php, src/flow/workflow/ICArcanistWorkflow.php, src/flow/workflow/ICCascadeWorkflow.php
We used wrong assumption that `arc diff` is rewriting first commit in change it actually amends the last one. This break cascading rebase when rebase conflict happens and we try to use alternative rebase based on `rebase --onto`.
=> [arc flow] Change how we detect base commit, from greping git log for Differential Revision to asking phabricator about Base commit

src/configuration/ArcanistSettings.php, src/workflow/ArcanistDiffWorkflow.php
This change adds a prompt to the user during a new revision creation to tag it with #autoland . Handles various cases to skip this prompt as well. It is gated behind the config flag `uber.differential.autoland-prompt`
Some screenshots in action:
=> [Autoland] Prompt user to tag with #autoland upon revision creation

src/workflow/ArcanistDiffWorkflow.php
Fix the below stacktrace
```
ERROR 8: Undefined index: summary at [/usr/local/Cellar/arcanist/tip/arcanist/src/workflow/ArcanistDiffWorkflow.php:2244]
arcanist
#0 ArcanistDiffWorkflow::shouldTagWithAutoland(array) called at [<arcanist>/src/workflow/ArcanistDiffWorkflow.php:486]
#1 ArcanistDiffWorkflow::run() called at [<arcanist>/scripts/arcanist.php:394]
```
=> Check for empty diff summary in autoland tagging workflow

src/workflow/ArcanistPatchWorkflow.php
- Use --depth=1 when fetching base ref from staging repository
- Remove '--tag' flag which is not applicable to 'git fetch'
=> Fetch using depth=1 with "--uber-use-staging-git-tags"

src/workflow/ArcanistPatchWorkflow.php
Further investigation has revealed this may have unintended side-effects.
=> Revert use of --depth=1 in --uber-use-staging-git-tags

src/workflow/ArcanistPatchWorkflow.php
When a diff has a base not present in the repository, try to fetch the specific base ref from staging and origin first before trying the potentially expensive 'git fetch --all'.
=> Try to fetch base ref explicitly before fetch all

src/uber/UberTask.php
Older operating systems provide php 5.6 which doesn't yet have Throwable as parent of Exception hence exception is not actually handled there
=> Fix unhandled exception for older php version

src/workflow/ArcanistBulkPatchWorkflow.php
Prevent failure of Filesystem::remove when cleaning up the temporary directory causing the entire command to fail.
=> Prevent temp dir cleanup from causing command failure

src/uber/UberTask.php
Limiting the view to only top 3 projects is too restrictive given how much time interactive issue creation saves.
Another problem with the current approach is that starting a new project or transferring teams will cause your new active project to be low rank and likely missing from the issue creation list for a while until you get more tasks.
=> Display all projects instead of top 3

src/workflow/ArcanistPatchWorkflow.php
`--uber-use-staging-git-tags` is always trying to fetch staging ref even if commit that ref is referring to is available in repository. Lets not do it if we have it in repository, this will save some roundtrip.
=> Do not fetch staging refs if we already have base hash in repository

src/workflow/ArcanistPatchWorkflow.php
Fetching by ref is slow on staging machines serving large repositories
=> Fetch staging ref by ref first before fetching by hash whenever we know diff ID

src/flow/workflow/ICFlowWorkflow.php
`arc flow somebranch` doesn't require anything from Phabricator it is either branching new branch or checking out already existing one hence no need for authenticated conduit client which does unnecessary connection to Phabricator.
=> [arc flow] Do not require network when only branching is requested

src/lint/engine/ArcanistLintEngine.php, src/lint/linter/ArcanistLinter.php, src/unit/engine/phutil/PhutilTestCase.php, src/workflow/ArcanistWorkflow.php
This combination does not make sense and PHP 8 errors with:
```
Private methods cannot be final as they are never overridden by other classes
```
Thus remove the redundant final from all such functions.
=> Remove final from private functions for PHP 8 compatibility

src/configuration/ArcanistSettings.php, src/land/UberArcanistSubmitQueueEngine.php, src/workflow/ArcanistLandWorkflow.php
This change adds `uber.differential.autoland-if-building` config option.
If option is set to `true` on `arc land` operation if revision has ongoing builds the process will add autoland tag only instead of pushing revision to SubmitQueue.
=> Tag revisions for autoland for ongoing builds

src/flow/workflow/ICSyncWorkflow.php
=> Add option to skip autoland during `arc sync`

src/workflow/ArcanistDiffWorkflow.php
Fixes `arc diff` failing when you try to create revision without underlying repository.
=> Do not check for paths when there is no repository under the hood

src/workflow/ArcanistDiffWorkflow.php
**Previous behavior**: 
`arc diff --nointeractive` will still prompt the user when there are large files in the diff (even though `--nointeractive` is set). 
**New behavior**: 
`arc diff --nointeractive` will no longer prompt the user, as long as we're in a non-TTY environment (for example, CI).
---
Required for GitHub migration, as our github-synchronizer buildkite job needs to create the revision from the GitHub PullRequest (even if there are large files).
=> bypass confirmation if non-tty and nointeractive is set

src/lint/engine/ArcanistLintEngine.php, src/workflow/ArcanistUnitWorkflow.php
Add support arc unit metrics tracking
Add LinterConfigurationName to lint tracker since InfoName can have spaces which are convenient for querying and metrics collecting
This PR for master and [PR#268](https://github.com/uber/arcanist/pull/268) for stable
=> Add support arc unit metrics tracking

src/lint/engine/ArcanistLintEngine.php, src/workflow/ArcanistUnitWorkflow.php
There are two separate calls beginLintServiceCall and endLintServiceCall - one at [executeLinterOnPaths](https://github.com/uber/arcanist/pull/269/files#diff-c78fc11d2ae1d737f30dbb6a981b6e90e9ceb4fc0bb1f7c9cca4fff318875964L579) and another at [executeDidLintOnPaths](https://github.com/uber/arcanist/pull/269/files#diff-c78fc11d2ae1d737f30dbb6a981b6e90e9ceb4fc0bb1f7c9cca4fff318875964L599) it leads that the same event tracks twice with different duration for  executeLinterOnPaths and executeDidLintOnPaths
1. Make tracking lint execution for executeLinterOnPaths and executeDidLintOnPaths together
2. Add paths for unit tracking
For local testing copy changed arcanist to local dir /usr/local/Cellar/arcanist/tip/arcanist and run arc diff --trace
=> Track lint execution for executeLinterOnPaths and executeDidLintOnPaths together

src/unit/engine/UberMultiTestEngine.php, src/workflow/ArcanistUnitWorkflow.php
Move unit tracking to UberMultiTestEngine for tracking each multi engine types - BazelTestEngine, CustomUnitTestEngine, ChecklistTestEngine, ExecuteCommandUnitTestEngine, etc.
Add as arguments (call the value paths for compatibility with previous changes at UberArcanistConfiguration for monorepos) unit.engine.command or build-system + target otherwise empty for tracking unit checks 
The related [PR](https://github.com/uber/arcanist/pull/272) for master
Tested locally by moving changes to /usr/local/Cellar/arcanist/tip/arcanist and run arc unit --trace
Note: ios monorepo has UberModifiedMultiTestEngine in which need make similar changes as well.
=> Move unit tracking to UberMultiTestEngine for tracking separate each multi engine

.gitignore, README.md, composer.json, composer.lock, rector.php, src/flow/model/ICFlowFeature.php, src/uber/UberUSSO.php, src/unit/ArcanistUnitTestResult.php, src/unit/engine/ArcanistUnitTestEngine.php, src/workflow/ArcanistDiffWorkflow.php
Applies [ExplicitNullableParamTypeRector](https://github.com/rectorphp/rector/blob/aff937886fc1bd7605bdc6f8d750174a15d890cf/docs/rector_rules_overview.md#php84) to the entire PHP codebase. Otherwise using PHP 8.4 breaks with deprecation warnings.
• This is the only breaking change when going from 8.3 -> 8.4
• This change is backwards compatible (works on php 8.3)
=> Use rector to perform codemod to php8.4

src/workflow/CompareCommitToRevisionWorkflow.php
The logic that determines if a local enlistment is required wasn't updated when we changed the `compare-commit-to-revision` command to  work against conduit.
=> [arc] Updating compare-commit-to-revision to correctly determine if a local enlistment is needed

src/workflow/ArcanistDiffBasedWorkflow.php
As part of implementing [Git over gRPC](https://docs.google.com/document/d/1_MRgPzcLigDP4LMgG4FCMLdaxU8srbMVcpZH5ig7ynM/edit?pli=1&tab=t.0) we will change to Git remotes used for local checkout of Object Config repositories.
gitolite@config.uber.internal:<repository-name> will be changed to oc://<repository-name>
This breaks arc integration with staging area.
There are currently [29 Object Config repositories](https://code.uberinternal.com/P737097) using staging area. In these cases arc will push the staging tags using the remote specified in Phabricator. Since Phabricator does allow to use custom remote scheme, e.g. oc://. So it is not possible to just change staging area configs to use gRPC remote. The solution is this case is to introduce a new field in .arcconfig file …
=> [arc] Implement support for staging area remote override in .arcconfig

src/workflow/ArcanistDiffWorkflow.php
Current: 
Repo owners who do not set "uber.diff.git.push.verify": true by default are not running pre-push hook on git push. 
This is not the default in git and just like all other git hooks, pre-push hooks should run. 
After this change:
"uber.diff.git.push.verify" config would not let you override running pre-push hooks.
=> Remove config that sets pre-push hook 

src/lint/linter/xhpast/rules/ArcanistParentMemberReferenceXHPASTLinterRule.php, src/lint/linter/xhpast/rules/ArcanistSelfMemberReferenceXHPASTLinterRule.php, src/lint/renderer/ArcanistConsoleLintRenderer.php, src/workflow/CompareCommitToRevisionWorkflow.php
- fixing issue where a missing new line was resulting in false positives. 
- fixed some random linter whitespace errors in other files.
=> [arc] Fixing false-positive cases in compare-commit-to-revision logic

src/workflow/ArcanistDiffWorkflow.php
I tested these changes locally with `arc diff` command.
Before changes:
1) I added invalid UTF-8 characters to the file:
`echo -e "\xC0\xAF Invalid UTF-8 characters" >> main.go`
2) I ran the command to attempt to create a diff:
`arc diff --nolint --nounit`
Output:
```
Provide explanation for skipping lint or press Enter to abort: skip
Provide explanation for skipping unit tests or press Enter to abort: skip
Invalid Content Encoding (Non-UTF8)
This diff includes a file which is not valid UTF-8 (it has invalid byte
sequences). You can either stop this workflow and fix it, or continue. If you
continue, this file will be marked as binary.
You can learn more about how Phabricator handles character encodings (and how
to configure encoding settings and detect and correct encoding problems) by …
```
=> [master branch] Implement automatically-convert-non-utf flag to automatically convert invalid UTF-8 sequences to binary.
